POST http://localhost:4000/cars
Content-Type: application/json

{
  "personalData": {
    "ownerName": "Lucas",
    "ownerNumber": 555444444,
    "ownerAddress": "Madrid"
  },
  "description": "Change lights",
  "maker": "Chevrolet",
  "carModel": "Spark",
  "estimatedDate": "2021-10-13",
  "carId": 3347,
  "km": 16098,
  "onMaintenance": true
}


###

GET http://localhost:4000/cars
Content-Type: application/json

###

DELETE http://localhost:4000/cars/60905ab1da8c002d7c125a97
Content-Type: application/json

###

PUT http://localhost:4000/cars/60904651f04e705144756ae1
Content-Type: application/json

{
  "estimatedDate": "2021/10/13"
}

###